package bean;
// Generated 09/12/2024 17:14:49 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VccCliente generated by hbm2java
 */
@Entity
@Table(name="vcc_cliente"
    ,catalog="db_viviane_carvalho"
)
public class VccCliente  implements java.io.Serializable {


     private int vccIdCliente;
     private String vccNome;
     private Date vccDataNasc;
     private String vccSexo;
     private String vccEmail;
     private String vccNumeroTelefone;
     private String vccCpf;
     private String vccEndereco;
     private Date vccDataCadastro;
     private String vccRg;
     private Date vccDataUltimaCompra;
     private String vccCep;
     private String vccStatusCliente;
     private String vccCidade;
     private String vccEstados;

    public VccCliente() {
    }

	
    public VccCliente(int vccIdCliente, String vccNome, String vccSexo, String vccEmail, String vccNumeroTelefone, String vccCpf, String vccEndereco, String vccRg, String vccCep, String vccStatusCliente, String vccCidade, String vccEstados) {
        this.vccIdCliente = vccIdCliente;
        this.vccNome = vccNome;
        this.vccSexo = vccSexo;
        this.vccEmail = vccEmail;
        this.vccNumeroTelefone = vccNumeroTelefone;
        this.vccCpf = vccCpf;
        this.vccEndereco = vccEndereco;
        this.vccRg = vccRg;
        this.vccCep = vccCep;
        this.vccStatusCliente = vccStatusCliente;
        this.vccCidade = vccCidade;
        this.vccEstados = vccEstados;
    }
   
     @Id 

    
    @Column(name="vcc_idCliente", unique=true, nullable=false)
    public int getVccIdCliente() {
        return this.vccIdCliente;
    }
    
    public void setVccIdCliente(int vccIdCliente) {
        this.vccIdCliente = vccIdCliente;
    }

    
    @Column(name="vcc_nome", nullable=false, length=45)
    public String getVccNome() {
        return this.vccNome;
    }
    
    public void setVccNome(String vccNome) {
        this.vccNome = vccNome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcc_dataNasc", length=10)
    public Date getVccDataNasc() {
        return this.vccDataNasc;
    }
    
    public void setVccDataNasc(Date vccDataNasc) {
        this.vccDataNasc = vccDataNasc;
    }

    
    @Column(name="vcc_sexo", nullable=false, length=1)
    public String getVccSexo() {
        return this.vccSexo;
    }
    
    public void setVccSexo(String vccSexo) {
        this.vccSexo = vccSexo;
    }

    
    @Column(name="vcc_email", nullable=false, length=80)
    public String getVccEmail() {
        return this.vccEmail;
    }
    
    public void setVccEmail(String vccEmail) {
        this.vccEmail = vccEmail;
    }

    
    @Column(name="vcc_numeroTelefone", nullable=false, length=11)
    public String getVccNumeroTelefone() {
        return this.vccNumeroTelefone;
    }
    
    public void setVccNumeroTelefone(String vccNumeroTelefone) {
        this.vccNumeroTelefone = vccNumeroTelefone;
    }

    
    @Column(name="vcc_cpf", nullable=false, length=14)
    public String getVccCpf() {
        return this.vccCpf;
    }
    
    public void setVccCpf(String vccCpf) {
        this.vccCpf = vccCpf;
    }

    
    @Column(name="vcc_endereco", nullable=false, length=45)
    public String getVccEndereco() {
        return this.vccEndereco;
    }
    
    public void setVccEndereco(String vccEndereco) {
        this.vccEndereco = vccEndereco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcc_dataCadastro", length=10)
    public Date getVccDataCadastro() {
        return this.vccDataCadastro;
    }
    
    public void setVccDataCadastro(Date vccDataCadastro) {
        this.vccDataCadastro = vccDataCadastro;
    }

    
    @Column(name="vcc_rg", nullable=false, length=9)
    public String getVccRg() {
        return this.vccRg;
    }
    
    public void setVccRg(String vccRg) {
        this.vccRg = vccRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcc_dataUltimaCompra", length=10)
    public Date getVccDataUltimaCompra() {
        return this.vccDataUltimaCompra;
    }
    
    public void setVccDataUltimaCompra(Date vccDataUltimaCompra) {
        this.vccDataUltimaCompra = vccDataUltimaCompra;
    }

    
    @Column(name="vcc_cep", nullable=false, length=9)
    public String getVccCep() {
        return this.vccCep;
    }
    
    public void setVccCep(String vccCep) {
        this.vccCep = vccCep;
    }

    
    @Column(name="vcc_statusCliente", nullable=false, length=10)
    public String getVccStatusCliente() {
        return this.vccStatusCliente;
    }
    
    public void setVccStatusCliente(String vccStatusCliente) {
        this.vccStatusCliente = vccStatusCliente;
    }

    
    @Column(name="vcc_cidade", nullable=false, length=30)
    public String getVccCidade() {
        return this.vccCidade;
    }
    
    public void setVccCidade(String vccCidade) {
        this.vccCidade = vccCidade;
    }

    
    @Column(name="vcc_estados", nullable=false, length=2)
    public String getVccEstados() {
        return this.vccEstados;
    }
    
    public void setVccEstados(String vccEstados) {
        this.vccEstados = vccEstados;
    }

}


