package bean;
// Generated 09/12/2024 17:14:49 by Hibernate Tools 4.3.1



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VccProdutos generated by hbm2java
 */
@Entity
@Table(name="vcc_produtos"
    ,catalog="db_viviane_carvalho"
)
public class VccProdutos  implements java.io.Serializable {


     private int vccIdProdutos;
     private String vccNome;
     private Date vccDataFabricacao;
     private String vccDescricao;
     private String vccMarca;
     private double vccPreco;
     private int vccEstoque;
     private String vccTamanho;
    
    public VccProdutos() {
    }

	
    public VccProdutos(int vccIdProdutos, String vccNome, String vccDescricao, String vccMarca, int vccPreco, int vccEstoque, String vccTamanho) {
        this.vccIdProdutos = vccIdProdutos;
        this.vccNome = vccNome;
        this.vccDescricao = vccDescricao;
        this.vccMarca = vccMarca;
        this.vccPreco = vccPreco;
        this.vccEstoque = vccEstoque;
        this.vccTamanho = vccTamanho;
    }
   
   
     @Id 

    
    @Column(name="vcc_idProdutos", unique=true, nullable=false)
    public int getVccIdProdutos() {
        return this.vccIdProdutos;
    }
    
    public void setVccIdProdutos(int vccIdProdutos) {
        this.vccIdProdutos = vccIdProdutos;
    }

    
    @Column(name="vcc_nome", nullable=false, length=80)
    public String getVccNome() {
        return this.vccNome;
    }
    
    public void setVccNome(String vccNome) {
        this.vccNome = vccNome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcc_dataFabricacao", length=10)
    public Date getVccDataFabricacao() {
        return this.vccDataFabricacao;
    }
    
    public void setVccDataFabricacao(Date vccDataFabricacao) {
        this.vccDataFabricacao = vccDataFabricacao;
    }

    
    @Column(name="vcc_descricao", nullable=false, length=100)
    public String getVccDescricao() {
        return this.vccDescricao;
    }
    
    public void setVccDescricao(String vccDescricao) {
        this.vccDescricao = vccDescricao;
    }

    
    @Column(name="vcc_marca", nullable=false, length=20)
    public String getVccMarca() {
        return this.vccMarca;
    }
    
    public void setVccMarca(String vccMarca) {
        this.vccMarca = vccMarca;
    }

    
    @Column(name="vcc_preco", nullable=false, precision=10)
    public double getVccPreco() {
        return this.vccPreco;
    }
    
    public void setVccPreco(double vccPreco) {
        this.vccPreco = vccPreco;
    }

    
    @Column(name="vcc_estoque", nullable=false)
    public int getVccEstoque() {
        return this.vccEstoque;
    }
    
    public void setVccEstoque(int vccEstoque) {
        this.vccEstoque = vccEstoque;
    }

    
    @Column(name="vcc_tamanho", nullable=false, length=10)
    public String getVccTamanho() {
        return this.vccTamanho;
    }
    
    public void setVccTamanho(String vccTamanho) {
        this.vccTamanho = vccTamanho;
    }

  @Override
    public String toString() {
        return this.getVccNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof VccProdutos) {
            VccProdutos produtos = (VccProdutos) obj;
            if (produtos.getVccIdProdutos()== this.getVccIdProdutos()) {
                return true;
            }
        }
        return false;
    }




}


