package bean;
// Generated 09/12/2024 17:14:49 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VccUsuario generated by hbm2java
 */
@Entity
@Table(name="vcc_usuario"
    ,catalog="db_viviane_carvalho"
)
public class VccUsuario  implements java.io.Serializable {


     private int vccIdUsuario;
     private String vccNome;
     private String vccApelido;
     private String vccCpf;
     private Date vccDataNasc;
     private String vccSenha;
     private int vccNivel;
     private String vccAtivo;

    public VccUsuario() {
    }

	
    public VccUsuario(int vccIdUsuario, String vccNome, String vccApelido, String vccCpf, String vccSenha, int vccNivel, String vccAtivo) {
        this.vccIdUsuario = vccIdUsuario;
        this.vccNome = vccNome;
        this.vccApelido = vccApelido;
        this.vccCpf = vccCpf;
        this.vccSenha = vccSenha;
        this.vccNivel = vccNivel;
        this.vccAtivo = vccAtivo;
    }
  
     @Id 

    
    @Column(name="vcc_idUsuario", unique=true, nullable=false)
    public int getVccIdUsuario() {
        return this.vccIdUsuario;
    }
    
    public void setVccIdUsuario(int vccIdUsuario) {
        this.vccIdUsuario = vccIdUsuario;
    }

    
    @Column(name="vcc_nome", nullable=false, length=50)
    public String getVccNome() {
        return this.vccNome;
    }
    
    public void setVccNome(String vccNome) {
        this.vccNome = vccNome;
    }

    
    @Column(name="vcc_apelido", nullable=false, length=25)
    public String getVccApelido() {
        return this.vccApelido;
    }
    
    public void setVccApelido(String vccApelido) {
        this.vccApelido = vccApelido;
    }

    
    @Column(name="vcc_cpf", nullable=false, length=11)
    public String getVccCpf() {
        return this.vccCpf;
    }
    
    public void setVccCpf(String vccCpf) {
        this.vccCpf = vccCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcc_dataNasc", length=10)
    public Date getVccDataNasc() {
        return this.vccDataNasc;
    }
    
    public void setVccDataNasc(Date vccDataNasc) {
        this.vccDataNasc = vccDataNasc;
    }

    
    @Column(name="vcc_senha", nullable=false, length=20)
    public String getVccSenha() {
        return this.vccSenha;
    }
    
    public void setVccSenha(String vccSenha) {
        this.vccSenha = vccSenha;
    }

    
    @Column(name="vcc_nivel", nullable=false)
    public int getVccNivel() {
        return this.vccNivel;
    }
    
    public void setVccNivel(int vccNivel) {
        this.vccNivel = vccNivel;
    }

    
    @Column(name="vcc_ativo", nullable=false, length=1)
    public String getVccAtivo() {
        return this.vccAtivo;
    }
    
    public void setVccAtivo(String vccAtivo) {
        this.vccAtivo = vccAtivo;
    }




}


