package bean;
// Generated 09/12/2024 17:14:49 by Hibernate Tools 4.3.1



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import tools.Util;

/**
 * VccVenda generated by hbm2java
 */
@Entity
@Table(name="vcc_venda"
    ,catalog="db_viviane_carvalho"
)
public class VccVenda  implements java.io.Serializable {


     private int idVccVenda;
     private VccCliente vccCliente;
     private VccFornecedor vccFornecedor;
     private Date vccDataVenda;
     private double vccTotalVenda;
   

    public VccVenda() {
    }

    public VccVenda(int idVccVenda, VccCliente vccCliente, VccFornecedor vccFornecedor, Date vccDataVenda, int vccTotalVenda) {
       this.idVccVenda = idVccVenda;
       this.vccCliente = vccCliente;
       this.vccFornecedor = vccFornecedor;
       this.vccDataVenda = vccDataVenda;
       this.vccTotalVenda = vccTotalVenda;
    }
   
     @Id 

    
    @Column(name="id_vcc_venda", unique=true, nullable=false)
    public int getIdVccVenda() {
        return this.idVccVenda;
    }
    
    public void setIdVccVenda(int idVccVenda) {
        this.idVccVenda = idVccVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vcc_cliente", nullable=false)
    public VccCliente getVccCliente() {
        return this.vccCliente;
    }
    
    public void setVccCliente(VccCliente vccCliente) {
        this.vccCliente = vccCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vcc_fornecedor", nullable=false)
    public VccFornecedor getVccFornecedor() {
        return this.vccFornecedor;
    }
    
    public void setVccFornecedor(VccFornecedor vccFornecedor) {
        this.vccFornecedor = vccFornecedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcc_dataVenda", length=10)
    public Date getVccDataVenda() {
        return this.vccDataVenda;
    }
    
    public void setVccDataVenda(Date vccDataVenda) {
        this.vccDataVenda = vccDataVenda;
    }

    
    @Column(name="vcc_totalVenda", nullable=false, precision=10)
    public double getVccTotalVenda() {
        return this.vccTotalVenda;
    }
    
    public void setVccTotalVenda(double vccTotalVenda) {
        this.vccTotalVenda = vccTotalVenda;
    }
    
     @Override
    public String toString() {
        return Util.intToStr(this.getIdVccVenda());
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof VccVenda) {
            VccVenda venda = (VccVenda) obj;
            if (venda.getIdVccVenda()== this.getIdVccVenda()) {
                return true;
            }
        }
        return false;
    }


}


