package bean;
// Generated 09/12/2024 17:14:49 by Hibernate Tools 4.3.1



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VccVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="vcc_vendas_produtos"
    ,catalog="db_viviane_carvalho"
)
public class VccVendasProdutos  implements java.io.Serializable {


     private int idVccVendasProdutos;
     private VccProdutos vccProdutos;
     private VccVenda vccVenda;
     private Date vccData;
     private int vccTotal;

    public VccVendasProdutos() {
    }

	
    public VccVendasProdutos(int idVccVendasProdutos, VccProdutos vccProdutos, VccVenda vccVenda, int vccTotal) {
        this.idVccVendasProdutos = idVccVendasProdutos;
        this.vccProdutos = vccProdutos;
        this.vccVenda = vccVenda;
        this.vccTotal = vccTotal;
    }
    public VccVendasProdutos(int idVccVendasProdutos, VccProdutos vccProdutos, VccVenda vccVenda, Date vccData, int vccTotal) {
       this.idVccVendasProdutos = idVccVendasProdutos;
       this.vccProdutos = vccProdutos;
       this.vccVenda = vccVenda;
       this.vccData = vccData;
       this.vccTotal = vccTotal;
    }
   
     @Id 

    
    @Column(name="id_vcc_vendas_produtos", unique=true, nullable=false)
    public int getIdVccVendasProdutos() {
        return this.idVccVendasProdutos;
    }
    
    public void setIdVccVendasProdutos(int idVccVendasProdutos) {
        this.idVccVendasProdutos = idVccVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vcc_produtos", nullable=false)
    public VccProdutos getVccProdutos() {
        return this.vccProdutos;
    }
    
    public void setVccProdutos(VccProdutos vccProdutos) {
        this.vccProdutos = vccProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vcc_venda", nullable=false)
    public VccVenda getVccVenda() {
        return this.vccVenda;
    }
    
    public void setVccVenda(VccVenda vccVenda) {
        this.vccVenda = vccVenda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcc_Data", length=10)
    public Date getVccData() {
        return this.vccData;
    }
    
    public void setVccData(Date vccData) {
        this.vccData = vccData;
    }

    
    @Column(name="vcc_Total", nullable=false, precision=10)
    public int getVccTotal() {
        return this.vccTotal;
    }
    
    public void setVccTotal(int vccTotal) {
        this.vccTotal = vccTotal;
    }




}


